---
- name: Deploy Openshift virtual cluster
  hosts: localhost
  vars:
    clusterName: "{{ lookup('ansible.builtin.env', 'OCP_CLUSTER_NAME') }}"
    ocpRelease: "{{ lookup('ansible.builtin.env', 'OCP_RELEASE_VERSION') }}"
    localPullSecretJson: "{{ lookup('ansible.builtin.env', 'LOCAL_SECRET_JSON') }}"
    sshPublicKey: "{{ lookup('ansible.builtin.env', 'SSH_PUB_KEY_PATH') }}"
    # Additional Settings:
    vmNetwork: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_NETWOTK_NAME') | default('baremetal', True) }}"
    baremetalCIDR_ipv4: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_CIDR_IPv4') | default('172.16.200.0/24', True) }}"
    baremetalCIDR_ipv6: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_CIDR_IPv6') | default('2620:52:0:1325::0/64', True) }}"
    apiIp: "{% set ip = lookup('ansible.builtin.env', 'HUB_CLUSTER_CIDR_IPv4') | default('172.16.200.0/24', True) | split('.') %}{{ ip[0] }}.{{ ip[1] }}.{{ ip[2] }}.3"
    ingressIp: "{% set ip = lookup('ansible.builtin.env', 'HUB_CLUSTER_CIDR_IPv4') | default('172.16.200.0/24', True) | split('.') %}{{ ip[0] }}.{{ ip[1] }}.{{ ip[2] }}.2"
    vmMem: 32000
    vmNumCPUs: 16
    vmDisks:
      - 200
      - 200
      - 50
      - 50
      - 20
      - 20
      - 20

  tasks:

    - name: Create virtual network
      tags:
      - create-net
      command: >
        kcli create network -c "{{ baremetalCIDR_ipv6 }}" -d "{{ baremetalCIDR_ipv4 }}" \
                            --domain telco5gran.eng.rdu2.redhat.com \
                            {{ vmNetwork }}
      when: "vmNetwork not in ansible_interfaces"

    - name: Create kcli settings from template
      template:
        src: templates/configs/kcli-ocp-cluster-deployment.yaml.j2
        dest: /opt/assets/kcli-ocp-cluster-deployment.yaml

    - name: Check virtual networks
      command: kcli list networks
      register: nets

    - name: Show virtual networks
      debug:
        msg: "{{ nets.stdout_lines }}"

    - name: Deploy cluster
      shell: |
        kcli create kube openshift --paramfile /opt/assets/kcli-ocp-cluster-deployment.yaml | tee /opt/assets/kcli_create_kube_openshift.log

    - name: Create systemd kcli plan Linux service
      template:
        src: templates/systemd/kcli-cluster-plan.service.j2
        dest: /etc/systemd/system/kcli-cluster-plan.service

    - name: Run kcli plan as Linux service
      service:
        name: kcli-cluster-plan.service
        state: started
        enabled: yes

    - name: Check virtual Hub Cluster
      shell: |
        kcli list plans
        echo
        kcli list vm
      register: plans

    - name: Show virtual Hub Cluster
      debug:
        msg: "{{ plans.stdout_lines }}"

###    # This should be a systemctl service instead...
###    - name: Create Tunnels
###      shell: |
###        nohup nc -l -k -p 443 -c "nc {{ apiIp }} 6443" &
###        nohup nc -l -k -p 6443 -c "nc {{ ingressIp }} 443" &
