---
- name: Deploy Openshift virtual cluster
  hosts: localhost
  vars:
    clusterName: "{{ lookup('ansible.builtin.env', 'OCP_CLUSTER_NAME') }}"
    clusterDomainName: "{{ lookup('ansible.builtin.env', 'OCP_CLUSTER_DOMAIN_NAME') }}"
    ocpRelease: "{{ lookup('ansible.builtin.env', 'OCP_RELEASE_VERSION') }}"
    localPullSecretJson: "{{ lookup('ansible.builtin.env', 'LOCAL_SECRET_JSON') }}"
    sshPublicKey: "{{ lookup('ansible.builtin.env', 'SSH_PUB_KEY_PATH') }}"
    # Additional Settings:
    hubNetwork: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_NETWOTK_NAME') | default('hubnetwork', True) }}"
    apiIp: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_API_ADDR') }}"
    ingressIp: "{{ lookup('ansible.builtin.env', 'HUB_CLUSTER_APPS_ADDR') }}"
    baremetalCIDR_ipv4: "{% set ip = apiIp | split('.') %}{{ ip[0] }}.{{ ip[1] }}.{{ ip[2] }}.0/24"
    vmMem: 32000
    vmNumCPUs: 16
    vmDisks:
      - 200
      - 200
      - 50
      - 50
      - 20
      - 20
      - 20

  tasks:

    - name: Assert destination dir exists
      file:
        path: /opt/assets/{{ hubNetwork }}
        recurse: yes
        state: directory

    - name: Define virtual network
      tags:
      - create-net
      copy:
        dest: "/opt/assets/{{ hubNetwork }}/libvirt-bridge-network-setup.xml"
        content: |
          <network>
            <name>{{ hubNetwork }}</name>
            <forward mode="bridge"/>
            <bridge name="{{ hubNetwork }}-dev"/>
          </network>

    - name: Create virtual network
      tags:
      - create-net
      shell: |
        virsh net-define /opt/assets/{{ hubNetwork }}/libvirt-bridge-network-setup.xml
        virsh net-start {{ hubNetwork }}
        virsh net-autostart {{ hubNetwork }}
        sleep 5

    - name: Create kcli settings from template
      tags:
      - create-net
      template:
        src: templates/configs/kcli-ocp-cluster-deployment.yaml.j2
        dest: /opt/assets/kcli-ocp-cluster-deployment.yaml

    - name: Check virtual networks
      tags:
      - create-net
      command: kcli list networks
      register: nets

    - name: Show virtual networks
      tags:
      - create-net
      debug:
        msg: "{{ nets.stdout_lines }}"

    - name: Deploy cluster
      shell: |
        kcli create kube openshift --paramfile /opt/assets/kcli-ocp-cluster-deployment.yaml | tee /opt/assets/kcli_create_kube_openshift.log

    - name: Create systemd kcli plan Linux service
      template:
        src: templates/systemd/kcli-cluster-plan.service.j2
        dest: /etc/systemd/system/kcli-cluster-plan.service

    - name: Run kcli plan as Linux service
      service:
        name: kcli-cluster-plan.service
        state: started
        enabled: yes

    - name: Check virtual Hub Cluster
      shell: |
        kcli list plans
        echo
        kcli list vm
      register: plans

    - name: Show virtual Hub Cluster
      debug:
        msg: "{{ plans.stdout_lines }}"

###    # This should be a systemctl service instead...
###    - name: Create Tunnels
###      shell: |
###        nohup nc -l -k -p 443 -c "nc {{ apiIp }} 6443" &
###        nohup nc -l -k -p 6443 -c "nc {{ ingressIp }} 443" &
